#################################################
## APPLICATION
#################################################

spring.application.name=notification-service

server.port=8084

#################################################
## EUREKA
#################################################

eureka.client.service-url.defaultZone=http://localhost:8762/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

#################################################
## RABBITMQ
#################################################

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=raditya
spring.rabbitmq.password=12345

#################################################
## EMAIL
#################################################

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=muhammadradityaaldri@gmail.com
spring.mail.password=kyfstwsyahpkfxui
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#################################################
## ACTUATOR
#################################################

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true