global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:8762

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:8083

  - job_name: 'auth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:8091

  - job_name: 'product'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:8081

  - job_name: 'pelanggan'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:8082

  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:8085

  - job_name: 'notification'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:8084

  - job_name: 'consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:8087

  - job_name: 'produser'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:8086