#################################################
## APPLICATION
#################################################

spring.application.name=produser

server.port=8086

#################################################
## EUREKA
#################################################

eureka.client.service-url.defaultZone=http://localhost:8762/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

#################################################
## RABBITMQ
#################################################

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=raditya
spring.rabbitmq.password=12345

#################################################
## ACTUATOR
#################################################

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true